-- Importado de https://pt.wikipedia.org/wiki/M%C3%B3dulo%3ACita%C3%A7%C3%A3o/CS1/Sugest%C3%B5es (Wikipédia em português, CC BY-SA 4.0).
-- Por favor adicione novas sugestões em ordem alfabética
-- A forma é: "['Erros'] = 'Correcção', -- língua de origem".
suggestions = {
    ['access-date'] = 'acessodata',
    ['accessdata'] = 'acessodata',
    ['accessdaymonth'] = 'acessodata',
    ['accessmonth'] = 'acessodata',
    ['accessmonthday'] = 'acessodata',
    ['accesso'] = 'acessodata',
    ['accessyear'] = 'acessodata',
    ['acesos'] = 'acessodata',
    ['acessado em'] = 'acessadoem',
    ['acessdate'] = 'acessodata',
    ['acessoano'] = 'acessodata',
    ['acessodiames'] = 'acessodata',
    ['acessomesdia'] = 'acessodata',
    ['address'] = 'url',
    ['airdate'] = 'dataemissao',
    ['annee'] = 'ano', -- francês
    ['année'] = 'ano', -- francês
    ['año'] = 'ano',
    ['año-original'] = 'orig-year',
    ['añoacceso'] = 'acessodata', -- Spanish, Italian
    ['ano2'] = 'ano',
    ['apellido'] = 'sobrenome', -- espanhol, italiano
    ['apellidos'] = 'autores', -- espanhol, italiano
    ['archive-date'] = 'arquivodata',
    ['archive-url'] = 'arquivourl',
    ['archiv-datum'] = 'archive-date', -- German
    ['archivedate'] = 'arquivodata',
    ['archiveurl'] = 'arquivourl',
    ['article'] = 'titulo',
    ['artist'] = 'outros',
    ['at'] = 'em',
    ['auflage'] = 'ediçãao', -- German
    ['auther'] = 'author',
    ['Autor'] = 'autor',
    ['Autorlink'] = 'autorlink',
    ['auteur institutionnel'] = 'autor', -- francês
    ['auteur'] = 'autor', -- francês
    ['auteur1'] = 'autor', -- francês
    ['auteur2'] = 'coautor', -- francês
    ['auteurs'] = 'autores', -- francês
    ['auther'] = 'autor',
    ['author link'] = 'autorlink',
    ['author-first'] = 'primeiro',
    ['author-last'] = 'ultimo',
    ['author-link'] = 'autorlink',
    ['author-link'] = 'autorlink',
    ['autor-mask'] = 'autor-mascara',
    ['autormask'] = 'autor-mascara',
    ['año'] = 'ano',
    ['añoacceso'] = 'acessodata',
    ['autthor'] = 'autor',
    ['band'] = 'volume', -- German
    ['booktitle'] = 'titulolivro',
    ['callsign'] = 'indicativo',
    ['cartography'] = 'cartografia',
    ['champ libre'] = 'outros', -- francês
    ['chapter-format'] = 'formato-capitulo',
    ['chapter-url'] = 'formato-capitulo',
    ['city'] = 'cidade',
    ['class'] = 'classe',
    ['coauthor'] = 'autor',
    ['coauthors'] = 'autores',
    ['coautore'] = 'autore',
    ['coautores'] = 'autores',
    ['codling'] = 'lingua',
    ['cognom'] = 'sobrenome', -- catalão
    ['collection'] = 'colecao', -- francês, inglês
    ['Colecção'] = 'colecao',
    ['Coleção'] = 'colecao',
    ['conference'] = 'conferencia',
    ['conference-format'] = 'formato-conferencia',
    ['consulta'] = 'acessodata',
    ['consultado el'] = 'acessodata',
    ['consultado']  = 'acessodata',
    ['consultado_el'] = 'acessodata',
    ['consultadoel'] = 'acessodata',
    ['consulte le'] = 'acessodata', -- francês
    ['consulté le'] = 'acessodata', -- francês
    ['consulté le'] = 'acessodata', -- francês
    ['contribution'] = 'obra',
    ['czasopismo'] = 'periódico', -- Polish
    ['dat'] = 'data',
    ['data dostępu'] = 'acessodata', -- Polish
    ['dataacceso'] = 'acessodata', -- espanhol
    ['date'] = 'data', -- inglês
    ['date2'] = 'data', -- inglês
    ['day'] = 'data',
    ['dead-url'] = 'urlmorta',
    ['deadurl'] = 'urlmorta',
    ['degree'] = 'grau',
    ['dia'] = 'data',
    ['diario'] = 'local',
    ['directeur1'] = 'editor', -- francês
    ['dispaly-editors'] = 'numero-editores',
    ['dispalyeditors'] = 'numero-editores',
    ['display-authors'] = 'numero-autores',
    ['displayauthors'] = 'numero-autores',
    ['distributor'] = 'publicado',
    ['ditorial']  = 'editora',
    ['docket'] = 'expediente',
    ['edición'] = 'edicao',
    ['editeur'] = 'editora', -- francês
    ['edition'] = 'edicao',
    ['edition'] = 'editora',
    ['editoin'] = 'edicao',
    ['editon'] = 'edicao',
    ['Editora'] = 'editora',
    ['Edição'] = 'edicao',
    ['editor-first'] = 'editor-nome',
    ['editor-last'] = 'editor-sobrenome',
    ['editor-mask'] = 'editor-mascara',
    ['editor1-first'] = 'editor1-nome',
    ['editor2-first'] = 'editor2-nome',
    ['editorial'] = 'editora',
    ['editorial'] = 'editora',
    ['editormask'] = 'editor-mascara',
    ['en ligne le'] = 'arquivodata', -- francês
    ['en'] = 'em',
    ['encilopedia'] = 'enciclopedia',
    ['encyclopædia'] = 'enciclopedia',
    ['ency'] = 'enciclopedia',
    ['enlaceautor'] = 'autorlink', -- espanhol, italiano
    ['episode'] = 'episodio',
    ['episode-link'] = 'titulolink',
    ['episodelink'] = 'titulolink',
    ['event-format'] = 'formato-conferencia',
    ['éditeur'] = 'editora',
    ['éditeur'] = 'editor', -- francês
    ['édition'] = 'edicao', -- francês
    ['fecha'] = 'data', -- espanhol, italiano
    ['fecha_acceso'] = 'acessodata',
    ['fecha_de_acceso'] = 'acessodata',
    ['fechaacceso'] = 'acessodata', -- espanhol, italiano
    ['fechaacesso'] = 'acessodata',
    ['fechaarchivo'] = 'arquivodata',
    ['fechaarchivo'] = 'arquivodata', -- espanhol, italiano
    ['fechacceso'] = 'acessodata',
    ['fechadeacceso'] = 'acessodata',
    ['fechadeaccesso'] = 'acessodata',
    ['fecharchivo'] = 'arquivodata',
    ['fonte'] = 'local',
    ['format'] = 'formato',
    ['foramt'] = 'formato',
    ['forfatter'] = 'autor', -- Norwegian
    ['frist'] = 'first',
    ['herausgeber'] = 'editors', -- German (singular and plural)
    ['hora'] = 'tempo',
    ['idioma2'] = 'lingua',
    ['idioma3'] = 'lingua',
    ['ignoreisbnerror']  = 'ignoreisbn',
    ['imię'] = 'first', -- Polish
    ['isbnistformalfalsch'] = 'ignore-isbn-error', -- German
    ['isnb'] = 'isbn',
    ['inset'] = 'requadro',
    ['interviewer'] = 'entrevistador',
    ['interviewers']  = 'entrevistadores',
    ['issue'] = 'numero',
    ['jahr'] = 'ano', -- German
    ['kapitel'] = 'capítulo', -- German
    ['lang'] = 'lingua',
    ['lang2'] = 'lingua',
    ['lang3'] = 'lingua',
    ['language'] = 'lingua',
    ['langue'] = 'lingua', -- francês
    ['lenda-tempo'] = 'legenda',
    ['lien auteur1'] = 'autorlink', -- francês
    ['lien auteur2'] = 'autorlink', -- francês
    ['lien auteur3'] = 'autorlink', -- francês
    ['lien editeur'] = 'editorlink', -- francês
    ['lien éditeur'] = 'editorlink', -- francês
    ['lieu'] = 'local', -- francês
    ['ling'] = 'lingua',
    ['lingua2'] = 'lingua', -- italiano
    ['lingua3'] = 'lingua', -- italiano
    ['linguagem'] = 'lingua', -- espanhol, italiano
    ['lire en ligne'] = 'url', -- francês
    ['lizenznummer'] = 'id', -- German (as 'id=License ...')
    ['loaction'] = 'location',
    ['locatoin'] = 'location',
    ['llengua'] = 'lingua', -- catalão
    ['localização'] = 'local',
    ['locação'] = 'local',
    ['língua2'] = 'lingua',
    ['língua3'] = 'lingua',
    ['magazine'] = 'revista', -- francês
    ['map'] = 'mapa',
    ['map-format'] = 'formato-mapa',
    ['map-url'] = 'urlmapa',
    ['medium'] = 'tipo',
    ['mes'] = 'data',
    ['miejsce'] = 'local', -- Polish
    ['miesiąc'] = 'data', -- Polish
    ['month'] = 'data',
    ['mês'] = 'data',
    ['mês'] = 'data',
    ['mês2'] = 'data',
    ['nazwisko'] = 'ultimo', -- Polish
    ['nespaper'] = 'jornal',
    ['newpaper'] = 'jornal',
    ['network'] = 'rede',
    ['news'] = 'jornal',
    ['newsgroup'] = 'grupo-noticias',
    ['miejsce'] = 'local', -- Polish
    ['miesiąc'] = 'data', -- Polish
    ['mois'] = 'data', -- French
    ['monat'] = 'data', -- German
    ['no-cat']  = 'nocat',
    ['nom'] = 'nome', -- francês, catalão
    ['nom1'] = 'nome', -- francês
    ['nom2'] = 'nome2', -- francês
    ['nombre'] = 'nome', -- espanhol, italiano
    ['nome Doi'] = 'doi',
    ['none'] = 'nome',
    ['notasedição'] = 'notas',
    ['notaspuborig'] = 'notas',
    ['notracking'] = 'nocat',
    ['número de edição'] = 'edicao',
    ['Numero'] = 'numero',
    ['Número'] = 'numero',
    ['odpowiedzialność'] = 'agencia', -- Polish
    ['offline'] = 'dead-url', -- German
    ['online'] = 'url', -- German (not a direct replacement, but can be emulated)
    ['opublikowany'] = 'agencia', -- Polish
    ['origdate'] = 'anooriginal',
    ['origyear'] = 'anooriginal',
    ['others'] = 'outros',
    ['otros'] = 'outros',
    ['opublikowany'] = 'agencia', -- Polish
    ['origdate'] = 'orig-year',
    ['originaljahr'] = 'anooriginal', -- German
    ['originalort'] = 'local', -- German (if 'ort' is specified at the same time, the latter should be put in 'publication-place')
    ['originalsprache'] = 'língua', -- German
    ['originaltitel'] = 'título', -- German (if 'originaltitel' is specified, any possible contents of 'title' should be put in 'trans-title')
    ['ort'] = 'local', -- German
    ['other'] = 'outros',
    ['oznaczenie'] = 'agência', -- Polish
--    ['page'] = 'pagina', -- francês
--    ['pages'] = 'paginas',
    ['Página'] = 'pagina',
    ['passage'] = 'pagina',
    ['periodique'] = 'periodico', -- francês
    ['place'] = 'local',
    ['pmcid'] = 'pmc',
    ['pmed'] = 'pmid',
    ['postnom1'] = 'apelido', -- francês
    ['postnom2'] = 'apelido', -- francês
    ['prenom1'] = 'nome', -- francês
    ['prenom2'] = 'nome', -- francês
    ['primeiro 1'] = 'primeiro',
    ['primero'] = 'primeiro',
    ['praca'] = 'work', -- Polish
    ['prénom'] = 'primeiro', -- francês
    ['pub'] = 'editora',
    ['publicación'] = 'editora',
    ['publicado por'] = 'publicado',
    ['publicadopor'] = 'publicado',
    ['publicador'] = 'editora',
    ['publication-date'] = 'data-publicacao',
    ['publication-place'] = 'local-publicacao',
    ['publicationdate'] = 'data-publicacao',
    ['publicationplace'] = 'local-publicacao',
    ['publicista'] = 'editora',
    ['publikasjon'] = 'periódico',    -- Norwegian: publication
    ['publishers'] = 'editora',
    ['pág'] = 'pagina',
    ['páxinaweb'] = 'website',
    ['périodique'] = 'periodico', -- francês
    ['quotation']  = 'cita',
    ['quotes'] = 'titulolivro',
    ['registration'] = 'registo',
    ['reihe'] = 'series', -- German
    ['Ref'] = 'ref',
    ['retrieved'] = 'acessodata',
    ['retrieved'] = 'acessodata',
    ['revista'] = 'publicacao',
    ['rok'] = 'data', -- Polish
    ['rótulo Doi'] = 'doi',
    ['sammelwerk'] = 'work', -- German
    ['scale'] = 'escala', -- inglês
    ['season'] = 'temporada',
    ['seiten'] = 'pages', -- German
    ['separator'] = 'modo', -- remove after 2016-01-01
    ['separador'] = 'modo', -- remove after 2016-01-01
    ['service'] = 'agencia',
    ['side'] = 'page', -- Norwegian
    ['site'] = 'website',
    ['sitio'] = 'obra',
    ['sitioweb'] = 'website', --Spanish
    ['sito'] = 'website',
    ['source'] = 'local', -- inglês
    ['stron'] = 'página', -- Polish
    ['strony'] = 'página', -- Polish
    ['spalten'] = 'at', -- German (not a direct replacement, but can be emulated)
    ['sprache'] = 'language', -- German
    ['suscripción'] = 'subscricao', -- espanhol, italiano
    ['station'] = 'estacao',
    ['stron'] = 'page', -- Polish
    ['strony'] = 'pages', -- Polish
    ['subject'] = 'entrevistado',
    ['subject-link'] = 'entrevistadolink',
    ['Subtítulo'] = 'subtitulo',
    ['subscription'] = 'subscricao',
    ['subtitle'] = 'subtitulo',
    ['subtítulo'] = 'subtitulo',
--    ['surname'] = 'ultimo',
    ['tempada'] = 'temporada',
    ['template doc demo']  = 'nocat',
    ['template-doc-demo']  = 'nocat',
    ['tile'] = 'titulo',
    ['time'] = 'tempo',
    ['time-caption'] = 'legenda',
    ['timecaption'] = 'legenda',
    ['tite'] = 'titulo',
    ['titel'] = 'titulo', -- German
    ['titel-p'] = 'titulo', -- German ('postscript=none' should be added as well)
    ['titelerg'] = 'contribution', -- German (not a direct replacement, but can be emulated)
    ['titlelink'] = 'titulolink',
    ['titol'] = 'titulo', -- catalão
    ['titolo'] = 'titulo', -- espanhol, italiano
    ['titre'] = 'titulo', -- francês
    ['tittel'] = 'title',    -- Norwegian
    ['Título'] = 'titulo',
    ['tome'] = 'numero', -- francês
    ['tomo'] = 'volume',
    ['traducteur'] = 'tradutor', -- francês
    ['traduction titre'] = 'titulo-trad', -- francês
    ['trans_title'] = 'titulo-trad', -- francês
    ['transchapter'] = 'trans-chapter',
    ['transcrición-url'] = 'urltranscricao',
    ['transcript'] = 'transcricao',
    ['transcript-url'] = 'urltranscricao',
    ['transcripturl'] = 'urltranscricao',
    ['translator'] = 'outros',
    ['transtitle'] = 'trans-title',
    ['typ'] = 'author-mask', -- German (not a direct replacement, but the only valid argument 'typ=wl' can be emulated using 'author-mask')
    ['type'] = 'tipo',
    ['tytuł'] = 'título', -- Polish
    ['títol'] = 'titulo', -- catalão
    ['títol'] = 'titulo', -- catalão
    ['ubicación'] = 'local', -- espanhol, italiano
    ['übersetzer'] = 'tradutor', -- German (singular and plural)
    ['universidade'] = 'instituicao',
    ['url texte'] = 'url', -- francês
    ['url_type'] = 'tipo',
    ['urlarchivo'] = 'arquivourl', -- espanhol, italiano
    ['urlarchivo'] = 'arqurivourl', -- Spanish, Italian
    ['urn'] = 'id', -- German (as 'id={{URN|...}}') (not yet supported by us directly)
    ['utgivelsesår'] = 'ano', -- Norwegian: release year
    ['verlag'] = 'editora', -- German
    ['version'] = 'arxiv',
    ['vol'] = 'volume',
    ['Volume'] = 'volume',
    ['volumen'] = 'volume', -- Spanish
    ['volumes'] = 'volume',
    ['Volumes'] = 'volume',
    ['vía'] = 'via',
    ['werk'] = 'obra', -- German
    ['werkerg'] = 'contribution', -- German (not a direct replacement, but can be emulated)
    ['wolumin'] = 'volume', -- Polish
    ['wydanie'] = 'número', -- Polish
    ['wydawca'] = 'editora', -- French
    ['xornal'] = 'jornal',
    ['year'] = 'ano',
    ['zaprezentowany'] = 'editora', -- French
    ['zdb'] = 'id', -- German (as 'id={{ZDB|...}}') (not yet supported by us directly)
    ['zitat'] = 'cita', -- German
    ['zugriff'] = 'acessodata' -- German
}


--[[--------------------------< P A T T E R N S >--------------------------------------------------------------

Here we use Lua patterns to make suggestions.  The form is ['pattern'] = 'correct',

Lua patterns are not regex though they are similar.  The escape character is '%', not '\'.  For more information about
lua patterns, see: Extension:Scribunto/Lua_reference_manual#Patterns

Patterns should probably always include the '^' and '$' anchor assertions to prevent a partial match from incorrectly
suggesting the wrong parameter name.  For instance, the pattern 'a[utho]+r' matches 'author' in the no-longer-supported
parameter |author-separator= so the code suggests '|author='; the same pattern also matches the no-longer-supported
parameter |separator= (returning 'ator') so again, the code suggests '|author='.

One capture is supported, typically the enumerator from an enumerated parameter (the '6' in |author6=, etc.)  The value from the
capture replaces $1 in the 'correct' value.

]]

local patterns = {
    ['^acess+o ?d?a?t?a?$'] = 'acessodata',
    ['^a[uto]+r$'] = 'autor',
    ['^a[uto]+r(%d+)$'] = 'autor$1',                                            -- enumerated
    ['^edi[tora]+s?$'] = 'editora',
    }

return {suggestions = suggestions, patterns=patterns};